# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIPENV_VENV_IN_PROJECT: "1"
  PIP_CACHE_DIR: "/cache/pip"
  PIPENV_SKIP_LOCK: "1"
  FLASK_ENV: "production"
  TEKID_ENV: "www"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

before_script:
  - python3.8 -V  # Print out python version for debugging
  - pip -V
  - pip install -r docs/requirements.txt

test:
  script:
    - python3.8 test_darc.py

pages:
  script:
    - make -C docs html
    - mv docs/build/html/ public
  artifacts:
    paths:
      - public
  only:
    - master
