version: '3'

services:
  darc:
    image: darc-debug
    build:
      context: .
      dockerfile: debug.dockerfile
    ports:
      - 9050:1086
    command: [ "https://www.nytimes3xbfgragh.onion", "https://www.bing.com" ]
    environment:
      ## [PYTHON] force the stdout and stderr streams to be unbuffered
      PYTHONUNBUFFERED: 1
      # reboot mode
      DARC_REBOOT: 1
      # debug mode
      DARC_DEBUG: 1
      # processes
      DARC_CPU: 10
      # multiprocessing
      DARC_MULTIPROCESSING: 0
      # multithreading
      DARC_MULTITHREADING: 0
      # data storage
      PATH_DATA: "data"
      # Tor proxy & control port
      TOR_PORT: 9050
      TOR_CTRL: 9051
      # Tor management method
      TOR_STEM: 1
      # Tor authentication
      TOR_PASS: "16:B9D36206B5374B3F609045F9609EE670F17047D88FF713EFB9157EA39F"
      # Tor bootstrap retry
      TOR_RETRY: 0
      # time delta for caches in seconds
      TIME_CACHE: 600
      # time to wait for selenium
      SE_WAIT: 60
      # extract link pattern
      LINK_EX: ".%2A%3F%5C.onion"
      # link black list
      LINK_BL: '[ "%28.%2A%5C.%29%3Ffacebookcorewwwi%5C.onion" ]'
    restart: "on-failure"
    volumes:
      - ./cache:/app/cache
      - ./data:/app/data
    stop_signal: SIGINT
