version: '2.1'

services:
  darc:
    image: darc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9065:9065
    command: [ "https://0day.today", "https://www.sjtu.edu.cn" ]
    environment:
      ## [PYTHON] force the stdout and stderr streams to be unbuffered
      PYTHONUNBUFFERED: 1
      # data storage
      PATH_DATA: "data"
      # Socks5 proxy & control port
      SOCKS_PORT: 9050
      SOCKS_CTRL: 9051
      # Tor authentication
      TOR_PASS: "16:B9D36206B5374B3F609045F9609EE670F17047D88FF713EFB9157EA39F"
      # Tor reset timeout
      TOR_RESET: 600
      # time delta in seconds
      TIME_DELTA: 600
    restart: "on-failure"
    volumes:
      - ./cache:/app/cache
      - ./data:/app/data
