version: '3'

services:
  darc:
    image: darc-debug
    build:
      context: .
      dockerfile: debug.dockerfile
    ports:
      - 9050:1086
    command: [ "https://www.nytimes3xbfgragh.onion", "https://www.bing.com" ]
    environment:
      ## [PYTHON] force the stdout and stderr streams to be unbuffered
      PYTHONUNBUFFERED: 1
      # reboot mode
      DARC_REBOOT: 1
      # debug mode
      DARC_DEBUG: 1
      # processes
      DARC_CPU: 10
      # multiprocessing
      DARC_MULTIPROCESSING: 0
      # multithreading
      DARC_MULTITHREADING: 0
      # time lapse
      DARC_WAIT: 60
      # data storage
      PATH_DATA: "data"
      # Tor proxy & control port
      TOR_PORT: 9050
      TOR_CTRL: 9051
      # Tor management method
      TOR_STEM: 1
      # Tor authentication
      TOR_PASS: "16:B9D36206B5374B3F609045F9609EE670F17047D88FF713EFB9157EA39F"
      # Tor bootstrap retry
      TOR_RETRY: 0
      # I2P port
      I2P_PORT: 4444
      # I2P bootstrap retry
      I2P_RETRY: 0
      # ZeroNet port
      ZERONET_PORT: 43110
      # ZeroNet bootstrap retry
      ZERONET_RETRY: 0
      # ZeroNet project path
      ZERONET_PATH: "/usr/local/src/zeronet"
      # time delta for caches in seconds
      TIME_CACHE: 600
      # time to wait for selenium
      SE_WAIT: 60
      # extract link pattern
      LINK_WHITE_LIST: '[ ".*?\\.onion", ".*?\\.i2p", "127\\.0\\.0\\.1:43110" ]'
      # link black list
      LINK_BLACK_LIST: '[ "(.*\\.)?facebookcorewwwi\\.onion" ]'
      # content type white list
      MIME_WHITE_LIST: '[ "text/html", "application/xhtml+xml" ]'
      # content type black list
      MIME_BLACK_LIST: '[ "text/css", "application/javascript", "text/json" ]'
    restart: "on-failure"
    volumes:
      # - ./cache:/app/cache
      - ./extra:/app/extra
      - ./data:/app/data
      - ./text:/app/text
